cgroups:
  - name: "services"
    config:
      cgroup.subtree_control: "+cpu +cpuset"
  - name: "services.throttled"
    config:
      cgroup.subtree_control: "+cpu +cpuset"
      cpu.max: 10000 # max 10 %

tasks:
  - name: sshd.tmpdir
    command: ["mkdir", "-p", "/var/run/sshd"]

services:
  - name: stress
    command: ["stress-ng", "-c", "1"]
    cgroup:
      name: "services.throttled"
      config:
        cpuset.cpus: 0  # Pin service to cpu0

  - name: ntpd
    command: ["/usr/sbin/ntpd", "-n", "-N", "-p", "/var/run/ntpd.pid"]

  - name: rsyslogd
    command: ["/usr/sbin/rsyslogd", "-n"]

  - name: sshd
    command: ["/usr/sbin/sshd", "-D"]
    conditions:
      - tasks.sshd.tmpdir.state.completed

sysctl:
  include:
    - /etc/sysctl.d/*.conf
  parameters:
    - key: net.ipv4.conf.all.forwarding
      value: 1
