tasks:
  - name: sshd.tmpdir
    command: ["mkdir", "-p", "/var/run/sshd"]

services:
  - name: ntpd
    command: ["/usr/sbin/ntpd", "-n", "-N", "-p", "/var/run/ntpd.pid"]

  - name: rsyslogd
    command: ["/usr/sbin/rsyslogd", "-n"]

  - name: sshd
    command: ["/usr/sbin/sshd", "-D"]
    conditions:
      - tasks.sshd.tmpdir.state.completed
