services:
  - name: "fail"
    command: ["sh", "-c", "sleep 5 && false"]
    conditions:
      - tasks.tmpdir.state.completed
    pidfile: 
      create: true
tasks:
  - name: "tmpdir"
    command: ["mkdir", "-p", "/tmp/tmpdir"]
