cgroups:  
  - name: "services"
    config:
      cgroup.subtree_control: "+cpu +cpuset"
  - name: "services.throttled"
    config:
      cgroup.subtree_control: "+cpu +cpuset"
      cpu.max: 10000 # max 10 %

modules:
  include:
    - /etc/modprobe.d/*.conf
  probe:
    - name: "netfilter"
      parameters: 
        - "udp=1"

filesystems:
  include:
    - /etc/fstab
  
services:
  - name: "stress"
    command: ["stress-ng", "-c", "1"]
    cgroup:
      name: services.throttled
      config:
        cpuset.cpus: "0" # Pin process to cpu0
  - name: "sleep"
    command: ["sh", "-c", "sleep 5"]
    pidfile: 
      create: true
  - name: "fail"
    command: ["sh", "-c", "sleep 50 && false"]
    conditions:
      - services.sleep.state.running
      - tasks.tmpdir.state.completed
    pidfile: 
      create: true

tasks:
  - name: "tmpdir"
    command: ["mkdir", "-p", "/tmp/tmpdir"]

sysctl:
  include:
    - /etc/sysctl.d/*.conf
  parameters:
    - key: net.ipv4.conf.all.forwarding
      value: 1
